# Generated by Django 4.1.1 on 2023-03-12 06:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinic", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name_plural": "Specialities",
            },
        ),
        migrations.CreateModel(
            name="Physician",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default.jpg",
                        max_length=120,
                        upload_to="physicians",
                        verbose_name="image",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        default="",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.speciality",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Physicians",
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="city",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="users.city"
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="physician",
            field=models.ForeignKey(
                default="",
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.physician",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="clinic",
            field=models.ForeignKey(
                default="",
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.clinic",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                default="",
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.patient",
            ),
        ),
    ]
