# Generated by Django 4.1.1 on 2023-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_alter_patient_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="id_number",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="identity number"
            ),
        ),
    ]
