# Generated by Django 4.1.1 on 2023-03-12 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("launch_date", models.DateField(verbose_name="Launch Date")),
                ("history", models.TextField(max_length=10000)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Dose_Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=99)),
                (
                    "abbrev_name",
                    models.CharField(max_length=10, verbose_name="Short Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=255)),
                (
                    "drug_dose",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="Dose"
                    ),
                ),
                (
                    "drug_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Price"
                    ),
                ),
                ("release_date", models.DateField(verbose_name="Release Date")),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Drug_Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("abbrev", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Scientific_Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                (
                    "dose",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="Dose"
                    ),
                ),
                (
                    "lethal_dose",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Lethal Dose",
                    ),
                ),
                (
                    "drug_unit",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.dose_unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                (
                    "comDrugID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pharmacy.drug"
                    ),
                ),
                (
                    "scientDrugID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.scientific_drug",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="drug",
            name="drug_form",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="pharmacy.drug_form",
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="drug_unit",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="pharmacy.dose_unit",
            ),
        ),
    ]
