# Generated by Django 4.2.6 on 2024-01-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dose_unit',
            options={'verbose_name': 'Dose Unit'},
        ),
        migrations.AlterModelOptions(
            name='drug_form',
            options={'verbose_name': 'Drug Form'},
        ),
        migrations.AlterModelOptions(
            name='scientific_drug',
            options={'verbose_name': 'Scientific Drug'},
        ),
        migrations.AlterField(
            model_name='drug',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pharmacy.company'),
        ),
    ]
