# Generated by Django 4.2.6 on 2024-01-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_dose_unit_options_alter_drug_form_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='company',
            name='history',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
