# Generated by Django 4.2.6 on 2024-01-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_remove_drug_expiry_date_remove_drug_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='dose',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Dose'),
        ),
    ]
