# Generated by Django 4.1.1 on 2023-04-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dummy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dummy",
            name="name",
            field=models.CharField(max_length=60, unique=True, verbose_name="name"),
        ),
    ]
