# Generated by Django 4.1.1 on 2023-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id_number",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="identity number"
            ),
        ),
    ]
