# Generated by Django 4.2.6 on 2024-01-09 17:58

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(default='default.jpg', max_length=120, upload_to='physicians', verbose_name='image')),
                ('speciality', models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='clinic.speciality')),
            ],
            options={
                'verbose_name_plural': 'Physicians',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='last name')),
                ('id_number', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='identity number')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='', max_length=1, verbose_name='gender')),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('U', 'Unspecified')], default='', max_length=1, verbose_name='marital status')),
                ('occupation', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='occupation')),
                ('image', models.ImageField(default='default.jpg', max_length=120, upload_to='patients', verbose_name='image')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.city')),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(verbose_name='Opening time')),
                ('closing_time', models.TimeField(verbose_name='Closing time')),
                ('is_archived', models.BooleanField(verbose_name='Inactive')),
                ('physician', models.ForeignKey(blank=True, default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='clinic.physician')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.TimeField(default=datetime.time, verbose_name='time')),
                ('appointment_number', models.SmallIntegerField(blank=True, default='0', verbose_name='appointment number')),
                ('clinic', models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
    ]
